server:
  port: 56045

spring:
  application:
    name: DynamicDataSource-example
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        # 主库数据源
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:23306/xxx?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: xxxxx
          password: xxxx
        ds0:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/ds0
          username: root
          password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml